kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitops-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp2
  volumeMode: Filesystem
