apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: php-hello-common
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: dev-stable
        url: https://kubernetes.default.svc
        namespace: namespace2
 