apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: php-hello-2
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: dev-stable
        url: https://kubernetes.default.svc
        namespace: namespace2
  template:
    metadata:
      name: '{{cluster}}-php-hello-2'
    spec:
      source:
        repoURL: https://gitlab.consulting.redhat.com/poc1/gitops-appdev.git
        targetRevision: main
        path: kustomize/org-services/services/namespace2/php-hello-2/overlays/{{cluster}}
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
  