apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: service2
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: dev-unstable
        url: https://kubernetes.default.svc
        namespace: value-add-unstable
  