apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |- 
    - op: add
      path: /spec/generators/0/list
      value:
        elements: 
        - cluster: dev-stable
          url: https://kubernetes.default.svc
          namespace: php-hello
        - cluster: dev-unstable
          url: https://kubernetes.default.svc
          namespace: php-hello-unstable
  target:
    kind: ApplicationSet
- patch: |- 
    - op: replace
      path: /spec/template/spec/source/path
      value: kustomize/org-services/common/overlays/dev
  target:
      name: php-hello-common



