apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: babboon
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: dev-stable
        url: https://kubernetes.default.svc
        namespace: namespace2
  template:
    metadata:
      name: '{{cluster}}-{{namespace}}-babboon'
    spec:
      source:
        repoURL: https://github.com/taiseerhussein/deploy-app-with-gitops.git
        targetRevision: main
        path: kustomize/org-services/services/namespace2/babboon/overlays/{{cluster}}
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
  