apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: service2
  namespace: ocp4-gitops-apps
spec:
  generators:
  - list:
      elements:
      # - cluster: dev-unstable
      #   url: https://kubernetes.default.svc
      #   namespace: value-add-unstable
      # - cluster: dev-stable
      #   url: https://kubernetes.default.svc
      #   namespace: value-add
  template:
    metadata:
      name: '{{cluster}}-service2'
    spec:
      source:
        repoURL: https://gitlab.consulting.redhat.com/poc1/gitops-appdev.git
        targetRevision: main
        path: namespace1/services/value-add/service2/overlays/{{cluster}}
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
