apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: profileservice
  namespace: ocp4-gitops-apps
spec:
  generators:
  - list:
      elements:
      # - cluster: dev-unstable
      #   url: https://kubernetes.default.svc
      #   namespace: value-add-unstable
      # - cluster: dev-stable
      #   url: https://kubernetes.default.svc
      #   namespace: value-add
  template:
    metadata:
      name: '{{cluster}}-profileservice'
    spec:
      source:
        repoURL: https://SFFCU-ITS@dev.azure.com/SFFCU-ITS/IT-SoftwareDevelopment/_git/olb-kustomize
        targetRevision: main
        path: schoolsfirst/services/value-add/profileservice/overlays/{{cluster}}
      project: olb
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
