apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tag-build-and-deploy
  namespace: tekton-tutorial
  labels:
    app.kubernetes.io/instance: pipeline
spec:
  params:
    - default: 'https://github.com/taiseerhussein/php-hello-dockerfile.git'
      description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: main
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - default: quay.io/tkhussein/php-hello
      description: image to be build from the code
      name: IMAGEREPO
      type: string
    - default: 'https://github.com/taiseerhussein/deploy-app-with-gitops.git'
      description: The kustomize git repository url
      name: KUSTOMIZE_GIT_URL
      type: string
    - default: dev-stable
      description: The target env
      name: KUSTOMIZE_ENV
      type: string
    - default: v3.0.4
      description: The target image tag
      name: IMAGETAG
      type: string
    - default: main
      description: The kustomize git repository revision
      name: KUSTOMIZE_GIT_REVISION
      type: string
    - default: kustomize/org-services/services
      description: The subdirectory in the kustomize git repository
      name: KUSTOMIZE_GIT_CONTEXT_DIR
      type: string
    - default: namespace1/php-hello/overlays/$(params.KUSTOMIZE_ENV)/version.yaml
      description: The YAML file in which to patch the image
      name: KUSTOMIZE_GIT_FILE_NAME
      type: string
  tasks:
    - name: build-image
      params:
        - name: IMAGE
          value: '$(params.IMAGEREPO):$(tasks.git-clone.results.commit)'
        - name: FORMAT
          value: docker
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.29.0
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: update-kustomize-repo
      params:
        - name: gitRepositoryUrl
          value: 'https://github.com/taiseerhussein/deploy-app-with-gitops.git'
        - name: gitRepositoryRevision
          value: main
        - name: gitPath
          value: kustomize/org-services/services
        - name: fileName
          value: namespace1/php-hello/overlays/dev-stable/version.yaml
        - name: image
          value: quay.io/tkhussein/php-hello
        - name: imageTag
          value: $(tasks.git-clone.results.commit)
        - name: verbose
          value: 'true'
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: update-kustomize-repo
  workspaces:
    - name: shared-workspace
