apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apm-secret
  namespace: backbase
spec:
  encryptedData:
    APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: AgBPsYrj7eeZwHowCi8/zqzn4iQhvIGZmNHWbLpY9z9xrfu4g/1bXe8gD33uExa61yVptdG7myvtw/lciT5fC+kKtT8kNRCknSU9guRuOa+bUQ7yMPUQkKY+iIBeTORX5S0bGFra5KIkHchGeoGx8816Rs4ueqhtI8X5UGb3vPnAbeaH1dGEFZ5WPBTYRdBEqkX1ZoOm43gKpbMCCxcEW/yNxEJxI4txNlz/SxycNFUINR+peVewQ5DiDX3X4fg97MHC8aU/8ersIjlc3uxz6bU6LH13EPAti+ok/ImIxKPi7K12dm1ExGhzAmPahwrKRe62UBr4sOfoYtW5naf+XAjGJRdAxP2g2cVNtHtKfwKLTvsEeJ/iBqxH4D5Hq4q8EzreByBhSCusSZaZGDUyckJcjsFb8y7udGocV4acywIpfVQBTY6Z8ozP5pW6rriyGA0ast0SC+9k9UuERcSviNc5pfcy7SpbEJ9agMWlfDy/P3ibtr/4CgsQvqhfZMw/ToxOwLBbPY3QMtlicIWkxz7DUZnPQ1WO3asHv0ZUrv/gIyqzNsdQiuyYjlmpJh3+pinPapwgbwEndE9hS+kgv7VntzAK57b2Wvr6vax/RAUraF1dDJ372eR3RPord9bN87RoM+PQZjLtlAcCF2dHIznWHT5hrXDv4Ogc9YlwgQw+3NbY+YC/rzyJwrnCE6jjbPjUfuEVcj8bP6c/xyqrI3zknj9gPsUB0OimjJmnmTYiKfRvmJU=
  template:
    metadata:
      creationTimestamp: null
      name: apm-secret
      namespace: backbase
    type: Opaque