apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: namespace2-test-secret
  namespace: namespace2
spec:
  encryptedData:
    key: AgBms9Zs8WcVwYCzNH1Nnzl7rMNEufxXMwUqY43VzcV4czfgr50JV2116BBO4PU07v7a8Y0DXF4vsZoqk5eaSe5fH3Ur7ygmauZ1mzZ1j42TrJgRiISZEgU5Gkgqw7N6ZYKMlgAi2KukBIn6LIWb7YrgmShCl0/aL9JzGIkrx/Gx98b+tGL7bd6SXVWhC7jdp4PuyPs+6jzqpjO1PmQ7tICpROw5qGGmOzhfxZaKeGPovO0CMXvwfPkz8gzCraZW03QUY4C1AAO0aPWpSAosD9D1yVgTbRVbjp453xjtJ3jlOClvy95IlUcOKx6Ig1leyT23+oa1qv1iMkcPHy8xpplArF+x3wKqURhWDVmXNrsFXiuF2HHl9xzdHY8uchIDSeT7MEcf4x7YfBybTh9Xg1aVkMdXy6jWso/EqhEdm182SFzliQZxxhy5nng8w7NfdG5Tt28nsquaeRjCNmEDk913OUiKiASCX4dzUb21gzB2US8OP6PnN/6bzD+/TYVVQYlGIMlMQn1lFdgYiDRwsjpof55bdG2GO+3eMpZWqeP/ADeA7atv3juS3o7sZpWVhQfkIptpqhpARUKJ4AcNfzsdItMtUnk6JerBWQURJOQIfnYwWhOGdEBaAbRy0UdZRYccfV9TAxsMaA/3toji48qVjICbl2gyyYRT4ysHNJOLFXxGzE8LQF9IIzHOF96ewaKPTMhJW0w=
  template:
    metadata:
      creationTimestamp: null
      name: namespace2-test-secret
      namespace: namespace2
    type: Opaque

