apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: activemq-secret
  namespace: backbase-unstable
spec:
  encryptedData:
    SPRING_ACTIVEMQ_PASSWORD: AgCAnA/n23CsqShLYo3ZYqLiG460i34tUo104bSV5RzgDSDSxG/EpLHZxu+JQJA3CHHf/bL2NfG0ggckE+jLYhJlidckI0EWWqWU7z3YmrtjmA7Qt5ZSJT8mHyfsXapiz5w6Ox9eLJG6/kirScum8CIufjtiZMyHyQS8nWo6HtexBZv2GW19iS2og38psqc9dqFh1eGTOgbgrw4xxUlKHggxZEi3geJqS8RjGlCAYDY9ZlBF77ksTydZAJ0yvyIzjR/oVle74XXNuQJ9R+Yd7dfclAxjDssPncYOrNuS9QJQdXLE6uIfxYUw4gpXcy9vKFMn4YjQkeUIPTUVDs0gpF13UPxow4gAvIYG/GWP54yQ6NiMJ/dud4Wuu2zKTMnSfpZeEAyHm1jTO1baOGdIlJrqIoCKY0zMdZ5AFW0KpqPnxW6xTdfH81tR1jZXfd+ED6/ze5ytdBfI/hP2nvpu22eKmFZkq119ZCvOix3M4NZr0dl0sgvYUSwcqRwAtjRdd1YqXBImhmTYE2qIpBhpHHELpfqlAMko4gO+XqyqbPdj3K75Bqk77i+zUuPrl38ROVIYoXyckooJZc/ViMpp9hzlBCM7Te1Nkk5h93c4IRjw4HuEX8mEuGK+0nCHiWE9UWeYI9IKqjH2YnrEH7z3dps29kRnGDEKyJZ3K7eSYoxrf4e7ZG4bxcE3xz1x9ig27TUowD3cbg==
    SPRING_ACTIVEMQ_USER: AgCFJ03WRZ47Kvlpvr8CzlbUAka8+BQz5qbdPZD9LrZQNeEI/E++f7gZI+VEeqKpPqEt4seah0LfGPSfGwQqYabRpKc8GncV9dtIfrdXhq0ocwos8bmEor2BJUBlgEvMMIz8hXMy6DN1HUjHwhF13R53/dNi2vfDS0efMF5cTqr87EtBYh2XvbOJggX/cORX9QUWcDfF8S1Vjdc2J89Xssw1Bs8rMYjcY7ntp05ysG3L0W2YGePF6kbLXaFhvN8CBxJWiW4C3/yUiJhISUBgwQmSvomkiHfQBPavFSrSkMLRYibKw8LRMsGB8eXOT0uaQQFL2C9ejlQkiJncTqkmgtAMlnVZmZb+OpiY0OSzwMDEr5q570lPes9MXq6WrCWvToJ6K9qt6JOKsXSZzmyz5vox1fTYxRrl2PflFYeHtgRvDEvMZWOIaHuwm1R3z1yvBAX4DplP6p45ikIK5grtCm/pkARg3RB5Im+4sLWvQBa9XFKfKLCa0nTVkJMUUZvD/C5cCpRzHRmqKe1XcujFezMemRsGeCfXvbQBAyoBJTiVFvLPmqfpibQIgDH0vpV+E0FgCgxOFu4ybZ0VPpmln6aO5JnAucCd0DD7JKhSvlAMgo2f95e+NP9TIv+Xz4lTAjyvhKXqTOIXwNCrIYkfdflDnYoJ9yrrayAHc+G6qYFtk596gbTbfGbkxnbMUGOaX+Eu7ZsvTw==
  template:
    metadata:
      creationTimestamp: null
      name: activemq-secret
      namespace: backbase-unstable
    type: Opaque