apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apm-secret
  namespace: backbase-unstable
spec:
  encryptedData:
    APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: AgBxA45kaEP5EZiPqINVIJ5HLwO5ecKqsw10k0e6/FQab+gYlkYSmQz/Jo36mZmY237RyMmGz/BM6GCShVilJ/jbzQDt5yZIL73vUv0Gl5IBkFk0EIEJ4N8LU9w2YRs0mdGs9G3yJAZvITn2jSLcPlMSQWNcZ6g1v4riKi2bMEObIrJWbRfgvDw74b8Mhv6zN4kxnUsLTqQ8TnjJ2EinVW9NR6GV766y9lffQ+eE0cSh8VLxyPSU3826szNRsnZKfE4PfhUMup6trtV3MBpnJds+C6GEPMX0rME4dvFucMdtkRtX2qupXPBJcKwbMhAVzlbZabvBPRpEbNHmw3nD6O0bnT0n5vbgwjXASuQHqc6pP5gRSGC7FD/MMz/nM1ohAoMz8GG1L1gO6to8vHyh5PR5rlbQWjnfTZQslyDARxSYK+Cd0M1Rer/TGvW61lemYBLxxbL0S00nV6fxS2NlZCRHR4vjgkT+jRtfTSnsopJx8pY7DZV6Irb+Cd0ytQ60TDETutEccMi2BxjHoyNZ29JwnBwUYfeERaOlitZd2po2uxS6+DSWLlm534/6GkifoiT74N/DY6yX8ujXp+kxGkatQqifj1xQNzMZReDb/BAvIb/GiILLWT6vIVZ2GSS6PgJlhaDFTDNMfCY/sF7C4PRghEXdFk/iGV1wkEESlXjkY53ZIdbPRp3J+TyZHITEALJ7ezzdCnfSWg3cvtye0v9rlieHiOdHZuiYZlub5mPOSlLzGlI=
  template:
    metadata:
      creationTimestamp: null
      name: apm-secret
      namespace: backbase-unstable
    type: Opaque
