apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestionservice
spec:
  template:
    spec:
      containers:
      - image: quay.octfcu.org/namespace1/ingestionservice:2022.09.28
        name: ingestionservice
