apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-hello
spec:
  template:
    spec:
      containers:
      - image: quay.io/tkhussein/php-hello:75220b9e95af89704f5ba7908b988824a6b2c7df
        name: php-hello
