apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-hello
spec:
  template:
    spec:
      containers:
      - image: quay.io/tkhussein/php-hello:4e8cc340ba986fcd7d306fc3ed03cdf76abf9ef5
        name: php-hello
