apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../org-services/namespace1/overlays/dev
- ../../org-services/namespace2/overlays/dev

# create namespaces appset. 
- ../../namespaces
# Create sealed secret appsets
- ../../sealed-secrets/dev

