apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: schoolsfirst-common-secrets
  namespace: ocp4-gitops-apps
spec:
  generators:
  - list:
      elements:
      # - cluster: dev
      #   url: https://kubernetes.default.svc
      #   namespace: namespace1
      # - cluster: dev
      #   url: https://kubernetes.default.svc
      #   namespace: namespace1-unstable
  template:
    metadata:
      name: '{{cluster}}-common-sealed-secret'
    spec:
      source:
        repoURL: https://SFFCU-ITS@dev.azure.com/SFFCU-ITS/IT-SoftwareDevelopment/_git/olb-kustomize
        targetRevision: main
        path: sealed-secrets/{{cluster}}
      project: olb
      destination:
        server: '{{url}}'
        namespace: ocp4-gitops-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true