apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace1-common-secrets
  namespace: ocp4-gitops-apps
spec:
  generators:
  - list:
      elements:
      # - cluster: dev
      #   url: https://kubernetes.default.svc
      #   namespace: namespace1
      # - cluster: dev
      #   url: https://kubernetes.default.svc
      #   namespace: namespace1-unstable
  template:
    metadata:
      name: '{{cluster}}-common-sealed-secret'
    spec:
      source:
        repoURL: https://gitlab.consulting.redhat.com/poc1/gitops-appdev.git
        targetRevision: main
        path: sealed-secrets/{{cluster}}
      project: default
      destination:
        server: '{{url}}'
        namespace: ocp4-gitops-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true