apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
# - php-hello-new-app-appset.yaml

patches:
- patch: |- 
    - op: add
      path: /spec/generators/0/list
      value:
        elements: 
        - cluster: dev-stable
          url: https://kubernetes.default.svc
          namespace: namespace3
  target:
    kind: ApplicationSet
- patch: |- 
    - op: replace
      path: /spec/template/spec/source/path
      value: kustomize/org-services/common/overlays/dev
  target:
    name: namespace3-common



