apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace3-common
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      # - cluster: dev
      #   url: https://kubernetes.default.svc
      #   namespace: php-hello
      # - cluster: dev
      #   url: https://kubernetes.default.svc
      #   namespace: php-hello-unstable
  template:
    metadata:
      name: '{{namespace}}-common'
    spec:
      source:
        repoURL: https://github.com/taiseerhussein/deploy-app-with-gitops.git
        targetRevision: main
        path: kustomize/org-services/common/overlays/{{cluster}}
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
 