apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: php-hello-new-app
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: dev-stable
        url: https://kubernetes.default.svc
        namespace: namespace3
  template:
    metadata:
      name: '{{cluster}}-{{namespace}}-php-hello-new-app'
    spec:
      source:
        repoURL: https://github.com/taiseerhussein/deploy-app-with-gitops.git
        targetRevision: main
        path: kustomize/org-services/services/namespace3/php-hello-new-app/overlays/{{cluster}}
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
  