kind: Deployment
apiVersion: v1
metadata:
  name: bam
spec:
  selector:
    app: bam
  template:
    metadata:
      labels:
        app: bam
        deploymentconfig: bam
    spec:
      volumes:
        - name: bam
          configMap:
            name: bam
            items:
              - key: BAM.log4j
                path: BAM.log4j
              - key: BAM.properties
                path: BAM.properties
              - key: rgy.pool.properties
                path: rgy.pool.properties
              - key: rgy.properties
                path: rgy.properties
            defaultMode: 420