apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../..namespace1php-hello/overlays/stage
- ../..namespace1value-add/overlays/stage
- ../../backbase/overlays/stage


# Create sealed secret appsets
- ../../sealed-secrets/stage
