apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../schoolsfirst/namespace1/overlays/stage
- ../../schoolsfirst/value-add/overlays/stage
- ../../backbase/overlays/stage


# Create sealed secret appsets
- ../../sealed-secrets/stage
