apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../namespace1/namespace1/overlays/stage
- ../../namespace1/value-add/overlays/stage
- ../../backbase/overlays/stage


# Create sealed secret appsets
- ../../sealed-secrets/stage
